### ISSUE TITLE
Кузница (со спрайтов луфа)

### ISSUE THREAD

**Issue by CrazySlM** [frosty-dev/white-dream-theta#11]
Херобора крафтищаяся на коленке ящеров с лаваленда, Для создания мечей топоров кирок и прочего. Не одними же копьями им воевать.
![изображение](https://user-images.githubusercontent.com/39928005/63983631-29837480-cad0-11e9-91a7-2191510c9635.png)

**Comment by Leviathan21** [comment]
да ты заебал

**Comment by n0rm4ld3f4ult** [comment]
давайте просто попросим ренди дать нам сборку луфа
