### ISSUE TITLE
Открутить спецэффекты от мутаций

### ISSUE THREAD

**Issue by Gargule** [frosty-dev/white-dream-theta#15]
Ещё со старо-тг бесит, что генетик светится как новогодняя ёлка. А с изменениями генетики, практическая функция этих спецэффектов теряется.

**Comment by Alexs410** [comment]
Лучше впилить генетическое скрытие, за 10 нестабильности. Надеюсь свободные слоты еще есть в коде.

**Comment by Gargule** [comment]
У меня есть вариант поприкольнее, если так не проканает

**Comment by CrazySlM** [comment]
Сокрытие можно даже без цены. Но сделать его скрытой мутацией которая получается путем скрещивания паранои и хамелеона.

**Comment by Alexs410** [comment]
С точки зрения баланса это хуйня. Халк, телекинез и термалы это 95% нестабильности. И если еще все это скрыть, то ты головой подумай, какой пиздец может случиться. Дварфизм за 5 и у тебя машина для робаста, способная закидывать всех и вся бегая по столам.
