### ISSUE TITLE
Делаем бесконечную еду

### ISSUE THREAD

**Issue by BadRyuner** [frosty-dev/white-dream-theta#20]
## Round ID: 1871

1) Берем любой орган (мозг, уши, язык или что-нибудь другое)
2) Жарим их в deep fryer
3) Тыкаем жаренным органом по бургеру и нам выпадает бургер с этим органом и сам орган, но только уже не в жаренном виде.
4) ???
5) Опять жарим этот орган и суем, получается бургер с двумя органами и опять этот же орган не в жаренном виде (я не могу обьяснить как он становиться опять не жаренным, какая-то ТГшная магия)
6) повторяем до бесконечности

**Comment by Alexs410** [comment]
Лучше написать это ТГшникам, так всем будет лучше.
