### ISSUE TITLE
Не верю что пишу это. Ксеногенка нужна, я поддерживаю Шрумана.

### ISSUE THREAD

**Issue by CrazySlM** [frosty-dev/white-dream-theta#24]
![изображение](https://user-images.githubusercontent.com/39928005/64570301-e0051600-d368-11e9-8734-2291dedbd33c.png)
Но я бы сделал так что бы она спавнилась только из плазмы с золотым экстрактом. И что бы такие эксперименты были РЕАЛЬНО опасны.

**Comment by Archemagus** [comment]
#23
