### ISSUE TITLE
 Кровь на полу [theta] 

### ISSUE THREAD

**Issue by CrazySlM** [frosty-dev/white-dream-theta#4]
Добавить в декали крови на полу реальную кровь с ДНК того кто её оставил.
Юзабельно для оживления полностью гибнутых.

**Comment by n0rm4ld3f4ult** [comment]
И как тогда триторам ПОЛНОСТЬЮ кого-то убить?

**Comment by RedFoxIV** [comment]
случайно открыл и охуел.

Тогда людям будет вообще похуй, если их убьют. Этой хуйнёй ты сводишь риск покинуть раунд со смертью к нулю и урезаешь gayplay тгбилда, оставляя тупой чай. Я понимаю (я надеюсь), что ты хочешь сделать из сервера бочку с ралиплеем, но это уже блять перебор

**Comment by Gargule** [comment]
Ну, во первых в оригинальном иссуе не было сказано ни слова про оживление. Во вторых, возьми мыло и ПРИМЕНИ ЕГО ПО НАЗНАЧЕНИЮ, А НЕ ДЛЯ РОБУСТА после убийства. В третьих, с текущей медициной и с текущими медиками у тебя шанс покинуть раунд не со смертью сводится к нулю сразу-же, как только ты порезал пальчик и пришёл лечиться в мед.
И в четвёртых: СВАЛИ НА МЕЙН, РЕФОКС!!!

**Comment by RedFoxIV** [comment]
ра ра ра
к чему бесконечный нёрф ролек, приближающийся к плинтусу? какой смысл он несёт?

`>СВАЛИ НА МЕЙН`
лучше локалочку подниму, тот же результат будет
