### ISSUE TITLE
ERP аля луфик. Кто сделает тот молодец.

### ISSUE THREAD

**Issue by CrazySlM** [frosty-dev/white-dream-theta#8]
Звуки "анимация" и анальный слот. Все как положено.

**Comment by TequilaSunrise272** [comment]
Я смотрю, у тя от луфика совсем крышак поехал.

**Comment by daxsc** [comment]
Привет луфозависимым из 20!9

**Comment by CrazySlM** [comment]
XD

**Comment by Leviathan21** [comment]
я в шутку сказал а вы всерьез будете её пилить чоле блядь

**Comment by Leviathan21** [comment]
ладно похуй если вы всерьез то брать отсюда
https://github.com/Tech3434/Techno-Phoenix

**Comment by qvazzar** [comment]
Ахуеть когда слот ануса...

**Comment by n0rm4ld3f4ult** [comment]
> 
> 
> ладно похуй если вы всерьез то брать отсюда
> https://github.com/Tech3434/Techno-Phoenix

у нас тогда был только ерп механ, там нету анального слота
и вообще это не ерп-механ это интеракт-панелька которая позволяет шлёпать-гладить-сосаться даже будучи одетым. 
а ну и по классике 
![изображение](https://user-images.githubusercontent.com/33929706/63993196-08cf1500-caf8-11e9-98e7-b686066fc73e.png)
